from .front_controllers import MyFrontController
from .about import About
from .index import Index
from .contact import Contact
from .course_categories import CourseCategories
from .students import Students
from .courses import Courses
from .create_category import CreateCategory
from .create_course import CreateCourse
